### ISSUE TITLE
Hello, is it possible to apply one-class classification to non-image area

### ISSUE THREAD

**Issue by stellarkey** [jeroenjanssens/phd-thesis#1]
For instance, vehicle runtime data. For detecting potential risk.

Thanks!

**Comment by jeroenjanssens** [comment]
Yes, the algorithms mentioned in the thesis are domain agnostic. As long as you provide a numerical feature matrix then you can apply all the algorithms. SOS also accepts a dissimilarity matrix directly in case you require a dissimilarity measure other than the Euclidean distance. Good luck.
